language: ruby
cache: bundler
rvm:
- 2.1.9
- 2.2.5
- 2.3.1
before_script:
- mysql -e 'create database enju_test'
- psql -c 'create database enju_test;' -U postgres
- bundle exec rake db:migrate
services:
- redis-server
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
notifications:
  slack:
    secure: ZbjsNTloRj5xbP5nRcwrqAJKC+6Kwo4M+J7Z+aXcHtKTzWfxfJw/aN47CrLm1afd8m+JPgEP3FjsXkOSBxfHiSwitZv4F6PjDaNcRXsv6gMI4dI+AhGTeXQuGtXDdYljipMVYAg0+Og3aVV7ZyesiugkLLMGV5d0TF/7mSVbWVs=
    rooms:
      secure: YqzX5RXBLPQYuDTb9NEEVj6O+yUMJbe7gEKH8lL7Yf334nrqFldavzNqHUZIq19foiqf5bM2VQ6UiOJP358Mqj7/xaGB4rdnK9wkrO0vGmzeGngEUSaUvTNFcf7EHoBIfJvNYfT7HoncN4g30gB7rOCnJ7lTXmuR+QSd9+cXxQo=
sudo: false
