language: ruby
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
before_script:
  - psql -c 'CREATE DATABASE enju_seed_dummy_test'
  - psql enju_seed_dummy_test -c 'CREATE EXTENSION pgcrypto'
  - bundle exec rake db:migrate
after_script:
  - bundle exec codeclimate-test-reporter
services:
  - redis-server
env:
  - DB=postgresql
sudo: false
addons:
  postgresql: "9.6"
